# Generated by Django 4.2.1 on 2023-07-12 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_followers_list_user_followers_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers_list',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
