# Generated by Django 4.2.1 on 2023-07-12 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_user_followers_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers_list',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
