# Generated by Django 4.2.1 on 2023-06-25 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlisted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
