# Generated by Django 4.2.1 on 2023-06-25 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
