# Generated by Django 4.2.1 on 2023-06-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_category_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
