# Generated by Django 4.2.3 on 2023-07-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilovetehping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
