# Generated by Django 4.2.3 on 2023-08-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilovetehping', '0004_alter_shop_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='price',
            new_name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
