# Generated by Django 4.2.3 on 2023-08-03 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilovetehping', '0005_rename_price_shop_rating_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
